package TcTools.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '50967372-bc45-4f8c-908e-44012f72ed5b' (id = 'TcTools')
accordingly and delete the patch script.
*/
changeProject("50967372-bc45-4f8c-908e-44012f72ed5b") {
    params {
        add {
            param("ccc", "")
        }
    }
}
