package TcTools.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2017_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = '54ad23a3-335f-431d-abaa-e336fcfff8fe' (id = 'TcTools_HttpsGithubComEgorminTcAgentToolsSyncRefsHeadsMaster')
in the project with uuid = '50967372-bc45-4f8c-908e-44012f72ed5b' and delete the patch script.
*/
create("50967372-bc45-4f8c-908e-44012f72ed5b", GitVcsRoot({
    uuid = "54ad23a3-335f-431d-abaa-e336fcfff8fe"
    id = "TcTools_HttpsGithubComEgorminTcAgentToolsSyncRefsHeadsMaster"
    name = "https://github.com/egormin/TC_agent_tools_sync#refs/heads/master"
    url = "https://github.com/egormin/TC_agent_tools_sync"
    authMethod = password {
        userName = "egormin"
        password = "credentialsJSON:8badbcc2-7a86-4432-b9a1-2b4a44c51888"
    }
}))

